# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('color_code', models.CharField(help_text='Add RGBA code of the course color. Example 25, 23, 255.', max_length=25, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course_description', models.TextField()),
                ('course_start_date', models.DateTimeField()),
                ('course_end_date', models.DateTimeField()),
                ('publish', models.BooleanField(default=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('open_registration', models.BooleanField(default=False)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('couch_email', models.EmailField(blank=True, max_length=125, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registration_form_link', models.URLField(blank=True, null=True)),
                ('course_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.CourseVenue')),
            ],
        ),
    ]
