# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(default=1), on_delete=django.db.models.deletion.CASCADE, to='courses.Category'),
            preserve_default=False,
        ),
    ]
