# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['updated_date'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(help_text='Add HEXA code of the course color. Example fffff.', max_length=25, unique=True),
        ),
    ]
