# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20160530_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['updated_date']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_admin',
            field=models.ForeignKey(blank=True, help_text='Automatic preffiled by currently log in user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, help_text='Course price in 2 digits format. Example 23.45.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venues.CourseVenue'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to the course, what to bring etc...', null=True),
        ),
    ]
