# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160530_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_admin',
            new_name='couch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='couch_email',
        ),
    ]
