# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20160530_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='couch',
            field=models.ForeignKey(blank=True, help_text='Automatic preffiled by currently log in user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
