# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 10:43
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_coursevenueauditlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_categoryauditlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouchAuditLogEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_couch', models.BooleanField(default=False)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_couch_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'ordering': ('-action_date',),
            },
        ),
        migrations.CreateModel(
            name='CourseAuditLogEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course_description', models.TextField()),
                ('course_start_date', models.DateTimeField()),
                ('course_end_date', models.DateTimeField()),
                ('publish', models.BooleanField(default=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('open_registration', models.BooleanField(default=False)),
                ('course_price', models.DecimalField(decimal_places=2, help_text='Course price in 2 digits format. Example 23.45.', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Notes to the course, what to bring etc...', null=True)),
                ('registration_form_link', models.URLField(blank=True, null=True)),
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_type', models.CharField(choices=[('I', 'Created'), ('U', 'Changed'), ('D', 'Deleted')], editable=False, max_length=1)),
                ('action_user', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_course_audit_log_entry', to=settings.AUTH_USER_MODEL)),
                ('couch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Couch')),
                ('course_category', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='courses.Category')),
                ('course_venue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venues.CourseVenue')),
            ],
            options={
                'default_permissions': (),
                'ordering': ('-action_date',),
            },
        ),
    ]
